name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      # - name: Restore CI Cache
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --ignore-scripts --frozen-lockfile
      - name: Copy Configuration
        run: |
          pushd src &&
          cp config.example.ts config.ts &&
          popd
      - name: Build code
        run: yarn build
